name: Bug Report
description: Report a bug in lambars
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Use this code...
        2. Call this function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: If possible, provide a minimal code example that reproduces the issue.
      render: rust
      placeholder: |
        use lambars::prelude::*;

        fn main() {
            // Your code here
        }

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.92.0-nightly"
    validations:
      required: true

  - type: input
    id: lambars-version
    attributes:
      label: lambars Version
      description: Version of lambars you're using
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
