name: Feature Request
description: Suggest a new feature for lambars
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, show what the API might look like.
      render: rust
      placeholder: |
        // Example usage
        use lambars::prelude::*;

        fn example() {
            // Proposed API usage
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I have also considered...

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module would this feature belong to?
      options:
        - typeclass
        - compose
        - control
        - persistent
        - optics
        - effect
        - derive
        - other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots about the feature request here.
